# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.6
_src_path: https://github.com/jupyterlab/extension-template
author_email: anastasiia.sliusar@quantstack.net
author_name: Anastasiia Sliusar
data_format: string
file_extension: ''
has_binder: true
has_settings: false
kind: server
labextension_name: jupyterlab-server-notification-ext
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extention to show notification after clicking
    on a button
python_name: jupyterlab_server_notification_ext
repository: https://github.com/AnastasiaSliusar/jupyterlab-server-notification-ext
test: true
viewer_name: ''

